print("welcome to ad libs!\n")

word1 = input("enter a name: ")
word2 = input("enter a item: ")
word3 = input("enter a candy: ")
word4 = input("enter a verb: ")
word5 = input("enter a bug: ")
word6 = input("enter a verb: ")
word7 = input("enter a color: ")
word8 = input("enter a verb: ")
word9 = input("enter a food: ")
word10 = input("enter a vehicle: ")
print(" a boy named " +  word1 + " was holding a  " +  word2 + " while eating a  " +  word3 + " ,he was  " +  word4 + "  down a hill then he got startled by a  " +  word5 + " then " +  word6 + " down into a " +  word7 + " river then " +  word8 + " he saw a " +  word9 + " then walked back up the hill and took his dad's " +  word10 + " then drove away with his " +  word2 +  "," +  word3 + " and his " +  word9 + " and was happy as ever. ")
input("\n enter any key to quit ")
